name: Fetch PR Data

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fetch_pr_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch PR data
        run: |
          mkdir -p content
          curl -s "https://api.github.com/repos/Iron-56/First-issue-test/pulls?state=all" | \
          jq '[.[] | {
            id: .id,
            number: .number,
            title: .title,
            state: .state,
            user: {
              login: .user.login,
              avatar_url: .user.avatar_url
            },
            created_at: .created_at,
            merged_at: .merged_at,
            body: .body,
            labels: (.labels | map({name})),
            html_url: .html_url
          }]' > content/pr_data.json
          
          echo "✅ Saved PR data to content/pr_data.json"
          cat content/pr_data.json

      - name: Commit and push changes using PAT
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add content/pr_data.json
          git diff --quiet && git diff --staged --quiet && echo "No changes to commit" && exit 0
          
          git commit -m "Update PR data"
          
          # Force push through PAT (replace OWNER/REPO with your actual repo)
          git push https://x-access-token:${TOKEN}@github.com/Iron-56/First-issue-test.git HEAD:main

      - name: Upload PR data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-data
          path: content/
          retention-days: 7
