name: Fetch PR Data

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fetch_pr_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch PR data with rate limit check and redirect fix
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          mkdir -p content
          
          # Fetch PRs using PAT and follow redirects
          RESPONSE=$(curl -s -L -H "Authorization: token ${TOKEN}" \
            "https://api.github.com/repos/Iron-56/First-issue-test/pulls?state=all")
          
          echo "GitHub API Response:"
          echo "$RESPONSE"
          
          # Check if response is an array (normal PR data) or object (error)
          IS_ARRAY=$(echo "$RESPONSE" | jq 'if type=="array" then true else false end')
          
          if [ "$IS_ARRAY" = "true" ]; then
            echo "$RESPONSE" | jq '[.[] | {
              id: .id,
              number: .number,
              title: .title,
              state: .state,
              user: {
                login: .user.login,
                avatar_url: .user.avatar_url
              },
              created_at: .created_at,
              merged_at: .merged_at,
              body: .body,
              labels: (.labels | map({name})),
              html_url: .html_url
            }]' > content/pr_data.json
            echo "Saved PR data to content/pr_data.json"
            cat content/pr_data.json
          else
            echo "API returned an error, redirect notice, or rate limit exceeded. Skipping update."
            echo "$RESPONSE" > content/pr_data_error.json
          fi

      - name: Commit and push changes using PAT
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add content/pr_data.json || true
          git diff --quiet && git diff --staged --quiet && echo "No changes to commit" && exit 0
          
          git commit -m "Update PR data"
          
          # Push changes via PAT
          git push https://x-access-token:${TOKEN}@github.com/Iron-56/First-issue-test.git HEAD:main

      - name: Upload PR data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-data
          path: content/
          retention-days: 7
